CREATE TABLE anime (
	id INT NOT NULL AUTO_INCREMENT,
	title TEXT,
    main_picture TEXT,
    start_date DATE,
    end_date DATE,
    synopsis TEXT,
	score DECIMAL(3,2),
    ranking INT,
    popularity INT,
    num_list_users INT,
    num_scoring_users INT,
    nsfw ENUM("white", "gray", "black"),
    created_at DATE,
    updated_at DATE,
    media_type ENUM("unknown","tv", "ova", "movie", "special",
		"ona", "music"),
	airing_status ENUM("not_yet_aired", "airing", "finished"),
    num_episodes INT,
    start_season TEXT,
    broadcast_date DATE,
    content_source TEXT,
    average_episode_duration INT,
    rating ENUM("g", "pg", "pg_13", "r", "r+", "rx"),
	PRIMARY KEY (id)
    );